import '@/styles/globals.scss'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Studio PianoLife',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
                <meta name="viewpo rt" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
                <link rel="icon" type="image/x-icon" href="/common/icon.ico"></link>

            </head>
            <body className={inter.className}>
                <Header />
                <div className='content'>
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    )
}
